(() => {
 "use strict";
 const cfg=window.PROTECTED_LIBRARY,gate=document.querySelector('#gate'),library=document.querySelector('#library'),groups=document.querySelector('#groups'),busy=document.querySelector('#busy');let key=null;
 const b64=(s)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
 async function derive(password){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:b64(cfg.salt),iterations:cfg.iterations},material,{name:'AES-GCM',length:256},false,['decrypt'])}
 async function decrypt(buffer,iv){return crypto.subtle.decrypt({name:'AES-GCM',iv:b64(iv)},key,buffer)}
 function render(){const by=Object.groupBy?Object.groupBy(cfg.resources,r=>r.group):cfg.resources.reduce((m,r)=>((m[r.group]??=[]).push(r),m),{});groups.innerHTML=Object.entries(by).map(([name,rows])=>`<section class="group"><h2>${esc(name)}</h2><div class="cards">${rows.map(r=>`<article class="card"><h3>${esc(r.title)}</h3><div class="chapters">${r.chapters.map((c,i)=>`<span>${i+1}. ${esc(c)}</span>`).join('')}</div><footer><small>${(r.bytes/1048576).toFixed(1)} MB · 加密 PDF</small><button class="open" data-id="${esc(r.id)}">解密打开</button></footer></article>`).join('')}</div></section>`).join('');document.querySelector('#count').textContent=cfg.resources.length}
 document.querySelector('#unlock').onsubmit=async(event)=>{event.preventDefault();const error=document.querySelector('#error');error.textContent='';try{key=await derive(document.querySelector('#password').value);const plain=await decrypt(b64(cfg.check),cfg.checkIv);if(new TextDecoder().decode(plain)!=='xiaotie-library-ok')throw new Error();gate.hidden=true;library.hidden=false;render()}catch{key=null;error.textContent='密码错误，无法解锁题库。'}};
 groups.onclick=async(event)=>{const button=event.target.closest('[data-id]');if(!button||!key)return;const item=cfg.resources.find(r=>r.id===button.dataset.id);const viewer=window.open('about:blank','_blank');if(viewer){viewer.opener=null;viewer.document.title='正在解密';viewer.document.body.textContent='正在解密 PDF，请稍候…'}busy.hidden=false;try{const response=await fetch(item.file,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const plain=await decrypt(await response.arrayBuffer(),item.iv);const url=URL.createObjectURL(new Blob([plain],{type:'application/pdf'}));if(viewer)viewer.location.replace(url);else{const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.click()}setTimeout(()=>URL.revokeObjectURL(url),5*60*1000)}catch(error){viewer?.close();alert(`资料打开失败：${error.message}`)}finally{busy.hidden=true}};
})();
