(() => {
  "use strict";
  const exams = window.MATH2_EXAMS || [];
  const bank = exams.flatMap((exam) => exam.items || []);
  const $ = (selector) => document.querySelector(selector);
  const els = { setup:$("#setup"),screen:$("#screen"),result:$("#result"),mode:$("#mode"),preset:$("#preset"),presetWrap:$("#presetWrap"),subject:$("#subject"),topic:$("#topic"),count:$("#count"),minutes:$("#minutes"),notice:$("#notice"),start:$("#start"),scope:$("#scope"),progress:$("#progress"),timer:$("#timer"),submit:$("#submit"),question:$("#question"),sheet:$("#sheet"),previous:$("#previous"),next:$("#next"),score:$("#score"),summary:$("#summary"),reviews:$("#reviews"),retry:$("#retry") };
  const state={questions:[],answers:[],current:0,seconds:0,deadline:0,timerId:null};
  const escapeHtml=(value)=>String(value??"").replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const isChoice=(item)=>String(item.kind||"").includes("选择");
  const choiceKey=(item)=>{if(!isChoice(item))return "";const match=String(item.answer||"").match(/[A-D]/i);return match?.[0]?.toUpperCase()||""};
  function seeded(items,seed){const rows=items.slice();let value=seed>>>0;const random=()=>{value=(value*1664525+1013904223)>>>0;return value/4294967296};for(let i=rows.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[rows[i],rows[j]]=[rows[j],rows[i]]}return rows}
  function refreshTopics(){const current=els.topic.value;const topics=[...new Set(bank.filter((item)=>!els.subject.value||item.subject===els.subject.value).map((item)=>item.topic))].sort();els.topic.innerHTML='<option value="">全部知识点</option>'+topics.map((topic)=>`<option>${escapeHtml(topic)}</option>`).join("");if(topics.includes(current))els.topic.value=current}
  function pool(){return bank.filter((item)=>(!els.subject.value||item.subject===els.subject.value)&&(!els.topic.value||item.topic===els.topic.value))}
  function fixedPaper(number){const seed=200000+Number(number)*6151;const latest=exams.slice().sort((a,b)=>b.year-a.year).slice(0,5).flatMap((exam)=>exam.items);const kindCounts=latest.reduce((map,item)=>(map[item.kind]=(map[item.kind]||0)+1,map),{});const total=Object.values(kindCounts).reduce((a,b)=>a+b,0)||1;const amount=22;const allocations=Object.entries(kindCounts).map(([kind,count])=>({kind,count:Math.floor(amount*count/total)}));let assigned=allocations.reduce((sum,row)=>sum+row.count,0);for(let i=0;assigned<amount;i=(i+1)%allocations.length){allocations[i].count++;assigned++}return seeded(allocations.flatMap((row,index)=>seeded(bank.filter((item)=>item.kind===row.kind),seed+index*71).slice(0,row.count)),seed+11)}
  function updateSetup(){const fixed=els.mode.value==='fixed';els.presetWrap.hidden=!fixed;els.subject.disabled=fixed;els.topic.disabled=fixed;els.count.disabled=fixed;els.notice.textContent=fixed?'十套卷按近五年选择、填空、解答题比例固定抽取 22 题；同套试卷题目保持稳定。':`当前范围共有 ${pool().length} 题，可按知识点随机抽题。`;els.start.textContent=fixed?`开始数学二模拟卷 ${els.preset.value}`:'开始专项模拟考试'}
  function typeset(node=document){return window.MathJax?.typesetPromise?window.MathJax.typesetPromise([node]).catch(()=>{}):Promise.resolve()}
  function start(){state.questions=els.mode.value==='fixed'?fixedPaper(els.preset.value):seeded(pool(),Date.now()).slice(0,Math.min(Number(els.count.value),pool().length));if(!state.questions.length)return;state.answers=state.questions.map(()=>null);state.current=0;state.seconds=Number(els.minutes.value)*60;state.deadline=Date.now()+state.seconds*1000;els.setup.hidden=true;els.result.hidden=true;els.screen.hidden=false;els.scope.textContent=els.mode.value==='fixed'?`数学二模拟卷 ${els.preset.value}`:(els.topic.value||els.subject.value||'数学二综合专项');clearInterval(state.timerId);state.timerId=setInterval(()=>{state.seconds=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));renderTimer();if(!state.seconds)submit(true)},1000);renderTimer();render()}
  function renderTimer(){els.timer.textContent=`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`}
  function render(){const item=state.questions[state.current],answer=state.answers[state.current];els.progress.textContent=`第 ${state.current+1}/${state.questions.length} 题`;const options=isChoice(item)?'<div class="choices">'+['A','B','C','D'].map((key)=>`<button type="button" data-choice="${key}" class="${answer===key?'selected':''}"><b>${key}</b><span>选择 ${key}</span></button>`).join('')+'</div>':`<div class="subjective"><textarea data-response placeholder="在这里写出主要步骤或答案">${escapeHtml(answer?.text||'')}</textarea><div class="self-buttons"><button type="button" data-self="mastered" class="${answer?.self==='mastered'?'selected':''}">我能独立完成</button><button type="button" data-self="review" class="${answer?.self==='review'?'selected':''}">需要复习</button></div></div>`;els.question.innerHTML=`<div class="question-meta"><span>${item.year} 年第 ${item.number} 题</span><span>${escapeHtml(item.kind)}</span><span>${escapeHtml(item.subject)}</span><span>${escapeHtml(item.topic)}</span></div><div class="stem">${escapeHtml(item.question).replaceAll('\n','<br>')}</div>${options}`;els.previous.disabled=state.current===0;els.next.textContent=state.current===state.questions.length-1?'检查答题卡 →':'下一题 →';renderSheet();typeset(els.question)}
  function renderSheet(){els.sheet.innerHTML=state.questions.map((_,index)=>`<button type="button" data-index="${index}" class="${state.answers[index]?'answered':''} ${index===state.current?'current':''}">${index+1}</button>`).join('')}
  function move(index){state.current=Math.max(0,Math.min(index,state.questions.length-1));render();scrollTo({top:0,behavior:'smooth'})}
  function submit(auto=false){if(!auto&&!confirm('确定交卷并查看成绩吗？'))return;clearInterval(state.timerId);const results=state.questions.map((item,index)=>{const answer=state.answers[index];return isChoice(item)?answer===choiceKey(item):answer?.self==='mastered'});state.questions.forEach((item,index)=>window.WrongBook?.capture({id:`math2-mock-${item.id}`,module:"数学二专题考试",subject:item.subject,topic:item.topic,prompt:item.question,options:isChoice(item)?['A','B','C','D'].map(key=>({key,text:`选择 ${key}`})):[],answer:isChoice(item)?choiceKey(item):item.answer,analysis:item.guide?.method||"按参考答案重新演算。",href:location.pathname},results[index]));const correct=results.filter(Boolean).length;const score=Math.round(correct/state.questions.length*100);els.screen.hidden=true;els.result.hidden=false;els.score.textContent=score;els.summary.textContent=`共 ${state.questions.length} 题，掌握 ${correct} 题，待复习 ${state.questions.length-correct} 题。选择题自动判分，主观题按你的自评计分。`;els.reviews.innerHTML=state.questions.map((item,index)=>`<article class="review ${results[index]?'correct':'wrong'}"><strong>第 ${index+1} 题 · ${results[index]?'掌握':'待复习'} · ${escapeHtml(item.topic)}</strong><p>${escapeHtml(item.question)}</p><div class="reference"><b>参考答案：</b>${escapeHtml(item.answer)}\n\n<b>复盘：</b>${escapeHtml(item.guide?.method||'按题干条件逐步推导，并核对公式适用范围。')}\n<b>易错点：</b>${escapeHtml(item.guide?.pitfall||'检查条件、符号和计算边界。')}</div></article>`).join('');typeset(els.result);scrollTo({top:0,behavior:'smooth'})}
  [...new Set(bank.map((item)=>item.subject))].forEach((subject)=>els.subject.insertAdjacentHTML('beforeend',`<option>${escapeHtml(subject)}</option>`));els.preset.innerHTML=Array.from({length:10},(_,index)=>`<option value="${index+1}">数学二模拟卷 ${index+1}</option>`).join('');refreshTopics();updateSetup();els.mode.onchange=updateSetup;els.preset.onchange=updateSetup;els.subject.onchange=()=>{refreshTopics();updateSetup()};els.topic.onchange=updateSetup;els.start.onclick=start;els.submit.onclick=()=>submit(false);els.retry.onclick=start;els.previous.onclick=()=>move(state.current-1);els.next.onclick=()=>move(state.current+1);els.sheet.onclick=(event)=>{const button=event.target.closest('[data-index]');if(button)move(Number(button.dataset.index))};els.question.onclick=(event)=>{const choice=event.target.closest('[data-choice]');if(choice){state.answers[state.current]=choice.dataset.choice;render()}const self=event.target.closest('[data-self]');if(self){const text=els.question.querySelector('[data-response]')?.value||'';state.answers[state.current]={text,self:self.dataset.self};render()}};els.question.oninput=(event)=>{if(event.target.matches('[data-response]')){const current=state.answers[state.current]||{self:''};state.answers[state.current]={...current,text:event.target.value};renderSheet()}};
})();
